const GameData=[
    {
        id:1,
        name:"melaka-mosque",
        pic:"https://assets.ccbp.in/frontend/react-js/melaka-mosque-img",
        isOpen:false
    },
    {
        id:2,
        name:"new-york",
        pic:"https://assets.ccbp.in/frontend/react-js/new-york-img.png",
        isOpen:false
    },
    {
        id:3,
        name:"escarpment",
        pic:"https://assets.ccbp.in/frontend/react-js/escarpment-img.png",
        isOpen:false
    },
    {
        id:4,
        name:"south-downs-national",
        pic:"https://assets.ccbp.in/frontend/react-js/south-downs-national-park-img.png",
        isOpen:false
    },
    {
        id:5,
        name:"melaka-mosque",
        pic:"https://assets.ccbp.in/frontend/react-js/melaka-mosque-img",
        isOpen:false
    },
    {
        id:6,
        name:"new-york",
        pic:"https://assets.ccbp.in/frontend/react-js/new-york-img.png",
        isOpen:false
    },
    {
        id:7,
        name:"escarpment",
        pic:"https://assets.ccbp.in/frontend/react-js/escarpment-img.png",
        isOpen:false
    },
    {
        id:8,
        name:"south-downs-national",
        pic:"https://assets.ccbp.in/frontend/react-js/south-downs-national-park-img.png",
        isOpen:false
    },
    {
        id:9,
        name:"escarpment",
        pic:"https://assets.ccbp.in/frontend/react-js/escarpment-img.png",
        isOpen:false
    }
]

export default GameData